### PR TITLE
Faro WIP

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
@MrJohn1911 tu pode botar o lps na mensagem do commit e depois rodar o analytics-cloud-acceptance de novo? por favor

obg

**Comment by catarineaguiar** [comment]
fyi @vinilopes20

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
Hey @ViniLopes20, could you take a look at this pull when you have time? thanks in advance!

**Comment by ViniLopes20** [comment]
Hey @MrJohn1911, I analyzed the Faro container log and observed these two errors that could be causing the problem in the AC build:

**Error 1 🐛:**
`2023-10-27 22:17:44.292 ERROR [Portal Dependency Manager Component Executor--1][PortalInstanceLifecycleListenerManagerImpl:444] null
java.lang.Exception: java.lang.NoSuchMethodError: 'com.liferay.expando.kernel.model.ExpandoColumn com.liferay.expando.kernel.service.ExpandoColumnLocalService.fetchColumn(long, java.lang.String)'
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.lambda$addingService$2(PortalInstanceLifecycleListenerManagerImpl.java:438) ~[?:?]
	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompany(CompanyLocalServiceImpl.java:498) ~[portal-impl.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor297.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy86.forEachCompany(Unknown Source) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.addingService(PortalInstanceLifecycleListenerManagerImpl.java:420) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.addingService(PortalInstanceLifecycleListenerManagerImpl.java:377) ~[?:?]
	at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerListImpl.java:164) ~[com.liferay.osgi.service.tracker.collections.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]`

**Error 2 🐛:**
`2023-10-27 22:17:56.118 ERROR [Portal Dependency Manager Component Executor--1][LogService:56] [Portal Dependency Manager Component Executor--1] Invocation of 'addApplication' failed.
org.apache.cxf.service.factory.ServiceConstructionException: null
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:220) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._registerApplication(CXFJaxRsServiceRegistrator.java:126) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._registerApplications(CXFJaxRsServiceRegistrator.java:136) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._rewire(CXFJaxRsServiceRegistrator.java:188) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._addApplication(CXFJaxRsServiceRegistrator.java:76) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._swapClassLoader(CXFJaxRsServiceRegistrator.java:213) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator.addApplication(CXFJaxRsServiceRegistrator.java:42) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:230) ~[bundleFile:?]`

You can see the full Faro log [here](https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/8129/functional-tomcat90-mysql57-jdk8/0/0/docker-logs/faro.1.log) 👀

**Pull request closed without merging**
